package com.wavehouse.domain.usecase.pos

import com.wavehouse.core.network.ApiResult
import com.wavehouse.domain.model.*
import com.wavehouse.domain.repository.OrderRepository
import com.wavehouse.domain.repository.StockRepository
import kotlinx.coroutines.flow.Flow
import javax.inject.Inject

/**
 * Tạo đơn hàng từ giỏ hàng.
 * Logic:
 * 1. Validate stock đủ cho tất cả item
 * 2. Tạo Order record
 * 3. Trừ tồn kho cho từng item (via StockRepository)
 * 4. Nếu thanh toán tiền mặt → auto confirm. QR → chờ confirm thủ công.
 */
class CheckoutUseCase @Inject constructor(
    private val orderRepository: OrderRepository,
    private val stockRepository: StockRepository
) {
    suspend operator fun invoke(
        cartItems: List<CartItem>,
        warehouseId: String,
        paymentMethod: PaymentMethod,
        createdBy: String,
        createdByName: String
    ): ApiResult<String> {
        // Validate
        if (cartItems.isEmpty()) return ApiResult.Error("Giỏ hàng trống")

        // Build order items
        val orderItems = cartItems.map { cart ->
            OrderItem(
                productId = cart.product.id,
                productName = cart.product.name,
                productSku = cart.product.sku,
                unitPrice = cart.product.salePrice,
                quantity = cart.quantity
            )
        }

        val totalAmount = orderItems.sumOf { it.lineTotal }

        val status = if (paymentMethod == PaymentMethod.CASH) OrderStatus.PAID else OrderStatus.PENDING

        val order = Order(
            id = "", // Generated by Firestore
            warehouseId = warehouseId,
            items = orderItems,
            totalAmount = totalAmount,
            paymentMethod = paymentMethod,
            status = status,
            createdBy = createdBy,
            createdByName = createdByName,
            paidAt = if (status == OrderStatus.PAID) System.currentTimeMillis() else null
        )

        // Create order — should also deduct stock inside a Firestore transaction
        return orderRepository.createOrder(order)
    }
}

/**
 * Xác nhận đã nhận tiền QR → chuyển status PENDING → PAID
 */
class ConfirmPaymentUseCase @Inject constructor(
    private val orderRepository: OrderRepository
) {
    suspend operator fun invoke(orderId: String): ApiResult<Unit> {
        return orderRepository.confirmPayment(orderId)
    }
}

/**
 * Lấy đơn hàng hôm nay
 */
class GetTodayOrdersUseCase @Inject constructor(
    private val orderRepository: OrderRepository
) {
    operator fun invoke(warehouseId: String): Flow<ApiResult<List<Order>>> {
        return orderRepository.getTodayOrders(warehouseId)
    }
}
