# Project-wide Gradle settings.
# https://docs.gradle.org/current/userguide/build_environment.html

# JVM memory for Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Enable Gradle configuration cache
org.gradle.configuration-cache=true

# Enable parallel builds
org.gradle.parallel=true

# Android Jetifier
android.useAndroidX=true

# Kotlin Coroutines debug agent
kotlinx.coroutines.debug=false

# Non-transitive R classes (reduces build times)
android.nonTransitiveRClass=true
