package com.wavehouse.domain.usecase.pos

import com.wavehouse.core.network.ApiResult
import com.wavehouse.domain.model.*
import com.wavehouse.domain.repository.OrderRepository
import com.wavehouse.domain.repository.StockRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.first
import javax.inject.Inject

/**
 * Tạo đơn hàng từ giỏ hàng.
 * Logic:
 * 1. Validate giỏ hàng không rỗng
 * 2. Validate tồn kho đủ cho TẤT CẢ item (trước khi ghi bất cứ gì)
 * 3. Tạo Order record + trừ tồn kho (qua OrderRepository)
 * 4. Nếu thanh toán tiền mặt → auto confirm. QR → chờ confirm thủ công.
 */
class CheckoutUseCase @Inject constructor(
    private val orderRepository: OrderRepository,
    private val stockRepository: StockRepository
) {
    suspend operator fun invoke(
        cartItems: List<CartItem>,
        warehouseId: String,
        paymentMethod: PaymentMethod,
        createdBy: String,
        createdByName: String
    ): ApiResult<String> {
        if (cartItems.isEmpty()) return ApiResult.Error("Giỏ hàng trống")

        // ── Bước 2: Validate tồn kho trước khi ghi bất cứ gì ─────────────────
        // Lấy 1 snapshot hiện tại từ Flow (bỏ qua Loading, lấy emit đầu tiên có data/error)
        val stockSnapshot: List<StockItem>
        val firstResult = stockRepository.getStockItems(warehouseId)
            .first { it !is ApiResult.Loading }

        when (firstResult) {
            is ApiResult.Success -> stockSnapshot = firstResult.data
            is ApiResult.Error -> return ApiResult.Error("Không thể kiểm tra tồn kho: ${firstResult.message}")
            ApiResult.Loading -> return ApiResult.Error("Không thể kiểm tra tồn kho")
        }

        val stockMap = stockSnapshot.associateBy { it.productId }
        val insufficientItems = cartItems.filter { cart ->
            val available = stockMap[cart.product.id]?.quantity ?: 0.0
            cart.quantity > available
        }

        if (insufficientItems.isNotEmpty()) {
            val itemNames = insufficientItems.joinToString(", ") { cart ->
                val available = stockMap[cart.product.id]?.quantity ?: 0.0
                "${cart.product.name} (cần ${cart.quantity}, tồn ${available})"
            }
            return ApiResult.Error("Tồn kho không đủ: $itemNames")
        }

        // ── Bước 3: Build order + tạo đơn ────────────────────────────────────
        val orderItems = cartItems.map { cart ->
            OrderItem(
                productId = cart.product.id,
                productName = cart.product.name,
                productSku = cart.product.sku,
                unitPrice = cart.product.salePrice,   // Giá bán snapshot cứng
                costPrice = cart.product.costPrice,   // Giá vốn MAC snapshot cứng
                quantity = cart.quantity
            )
        }

        val totalAmount = orderItems.sumOf { it.lineTotal }
        val status = if (paymentMethod == PaymentMethod.CASH) OrderStatus.PAID else OrderStatus.PENDING

        val order = Order(
            id = "", // Generated by RTDB push
            warehouseId = warehouseId,
            items = orderItems,
            totalAmount = totalAmount,
            paymentMethod = paymentMethod,
            status = status,
            createdBy = createdBy,
            createdByName = createdByName,
            paidAt = if (status == OrderStatus.PAID) System.currentTimeMillis() else null
        )

        return orderRepository.createOrder(order)
    }
}

/**
 * Xác nhận đã nhận tiền QR → chuyển status PENDING → PAID
 */
class ConfirmPaymentUseCase @Inject constructor(
    private val orderRepository: OrderRepository
) {
    suspend operator fun invoke(orderId: String): ApiResult<Unit> {
        return orderRepository.confirmPayment(orderId)
    }
}

class CancelOrderUseCase @Inject constructor(
    private val orderRepository: OrderRepository
) {
    suspend operator fun invoke(orderId: String): ApiResult<Unit> {
        return orderRepository.cancelOrder(orderId)
    }
}

/**
 * Lấy đơn hàng hôm nay
 */
class GetTodayOrdersUseCase @Inject constructor(
    private val orderRepository: OrderRepository
) {
    operator fun invoke(warehouseId: String): Flow<ApiResult<List<Order>>> {
        return orderRepository.getTodayOrders(warehouseId)
    }
}
